import React, { useState, useMemo, useEffect } from 'react';
import { Target, TrendingUp, DollarSign, Calendar, Sparkles, CheckCircle2, Download } from 'lucide-react';
import { useCurrency } from '../context/CurrencyContext';
import { calculateSavingsGoal } from '../utils/financialMath';
import { Card } from '../components/common/Card';
import { SliderField } from '../components/common/SliderField';
import { MetricCard } from '../components/common/MetricCard';
import { ExplainableResult } from '../components/common/ExplainableResult';
import { ShareButton, PrintButton } from '../components/common/ShareButton';
import { useShareableState } from '../hooks/useShareableState';
import { ExplainableResultData } from '../types/calculators';

export const SavingsGoalCalculator: React.FC = () => {
  const { currencyConfig, format } = useCurrency();
  const { updateUrlParams, getUrlParams, copyShareableLink, copied } = useShareableState();

  const initialParams = useMemo(() => getUrlParams(), []);

  const [targetAmount, setTargetAmount] = useState<number>(() => {
    const val = initialParams.get('target');
    return val ? parseFloat(val) : 0;
  });
  const [currentSavings, setCurrentSavings] = useState<number>(() => {
    const val = initialParams.get('current');
    return val ? parseFloat(val) : 0;
  });
  const [timeframeMonths, setTimeframeMonths] = useState<number>(() => {
    const val = initialParams.get('months');
    return val ? parseInt(val, 10) : 0;
  });
  const [annualReturnRate, setAnnualReturnRate] = useState<number>(() => {
    const val = initialParams.get('rate');
    return val ? parseFloat(val) : 0;
  });

  useEffect(() => {
    updateUrlParams({
      calc: 'savings-goal',
      target: targetAmount,
      current: currentSavings,
      months: timeframeMonths,
      rate: annualReturnRate,
    });
  }, [targetAmount, currentSavings, timeframeMonths, annualReturnRate, updateUrlParams]);

  const results = useMemo(() => {
    return calculateSavingsGoal({
      targetAmount,
      currentSavings,
      timeframeMonths,
      annualReturnRate,
    });
  }, [targetAmount, currentSavings, timeframeMonths, annualReturnRate]);

  const explainableData: ExplainableResultData = useMemo(() => {
    return {
      title: 'Savings Goal Feasibility & Contribution Strategy',
      summary: `To achieve your financial goal of ${format(targetAmount)} within ${timeframeMonths} months starting with ${format(currentSavings)} at an expected ${annualReturnRate}% annual return, you must deposit ${format(results.requiredMonthlyDeposit)} monthly. Over the term, compounding will generate ${format(results.interestEarned)} in interest.`,
      keyFigures: [
        { label: 'Required Monthly Deposit', value: format(results.requiredMonthlyDeposit), highlight: true },
        { label: 'Goal Target Amount', value: format(targetAmount) },
        { label: 'Current Progress', value: `${results.progressPercentage.toFixed(1)}%` },
        { label: 'Total You Will Deposit', value: format(results.totalDeposited) },
        { label: 'Compounded Interest Earned', value: format(results.interestEarned), hint: 'Wealth generated by compounding' },
        { label: 'One-Time Lump Sum Needed Today', value: format(results.lumpSumNeededToday), hint: 'If invested completely today at same return' },
      ],
      assumptions: [
        { label: 'Time Horizon', value: `${timeframeMonths} Months (${(timeframeMonths / 12).toFixed(1)} years)` },
        { label: 'Reinvestment Rate', value: `${annualReturnRate}% annual yield compounded monthly` },
        { label: 'Contribution Timing', value: 'Regular deposits made at the beginning of each monthly cycle' },
      ],
      methodology: 'Future Value of Annuity formula back-solving periodic payment (PMT) with starting capital compounding.',
      formulaSteps: [
        {
          name: 'Required Monthly Contribution (PMT)',
          formula: 'PMT = [Target - Current * (1 + r)^n] / [((1 + r)^n - 1) / r]',
          substituted: `[${format(targetAmount)} - ${format(currentSavings)} * (1 + ${(annualReturnRate / 1200).toFixed(5)})^${timeframeMonths}] / ...`,
          result: format(results.requiredMonthlyDeposit),
          explanation: 'Calculates the exact periodic liquidity required to meet the terminal balance target.',
        },
      ],
      disclaimers: [
        'Investment returns fluctuate and capital gains are not guaranteed unless held in government treasury bills or insured fixed deposits.',
        'Inflation will erode nominal purchasing power over extended multi-year horizons.',
      ],
    };
  }, [results, targetAmount, currentSavings, timeframeMonths, annualReturnRate, format]);

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-slate-200/80 dark:border-slate-800/80 pb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 text-xs font-semibold rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300">
              Savings & Investment Suite
            </span>
            <span className="text-xs text-slate-500 dark:text-slate-400">Target Accumulation Engine</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
            Savings Goal & Target Planner
          </h1>
          <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">
            Calculate the exact monthly deposit or upfront lump sum needed to achieve any financial milestone on schedule.
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <ShareButton onShare={copyShareableLink} copied={copied} />
          <PrintButton />
        </div>
      </div>

      {/* Top Metrics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard
          label="Required Monthly Deposit"
          value={format(results.requiredMonthlyDeposit)}
          icon={<Target className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />}
          subValue={`For next ${timeframeMonths} months`}
          variant="primary"
        />
        <MetricCard
          label="Starting Progress"
          value={`${results.progressPercentage.toFixed(1)}%`}
          icon={<CheckCircle2 className="w-5 h-5 text-blue-600 dark:text-blue-400" />}
          subValue={`${format(currentSavings)} of ${format(targetAmount)}`}
        />
        <MetricCard
          label="Interest Earned"
          value={format(results.interestEarned)}
          icon={<TrendingUp className="w-5 h-5 text-purple-600 dark:text-purple-400" />}
          subValue="Gained through compounding"
        />
        <MetricCard
          label="Lump Sum Alternative"
          value={format(results.lumpSumNeededToday)}
          icon={<Sparkles className="w-5 h-5 text-amber-600 dark:text-amber-400" />}
          subValue="If funded 100% upfront today"
        />
      </div>

      {/* Progress Bar Visualizer */}
      <Card className="!p-5">
        <div className="flex justify-between items-center text-xs font-semibold mb-2">
          <span className="text-slate-700 dark:text-slate-300">Goal Target Progress</span>
          <span className="text-emerald-600 dark:text-emerald-400">
            {format(currentSavings)} / {format(targetAmount)} ({results.progressPercentage.toFixed(1)}%)
          </span>
        </div>
        <div className="w-full h-3.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden p-0.5">
          <div
            className="h-full bg-gradient-to-r from-emerald-500 to-teal-400 rounded-full transition-all duration-500"
            style={{ width: `${Math.min(100, results.progressPercentage)}%` }}
          />
        </div>
      </Card>

      {/* Inputs & Summary Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-6 space-y-6">
          <Card>
            <h2 className="text-base font-bold text-slate-900 dark:text-white mb-4">
              Goal Parameters
            </h2>
            <div className="space-y-5">
              <SliderField
                label="Target Financial Goal"
                value={targetAmount}
                onChange={setTargetAmount}
                min={0}
                max={100_000_000}
                step={100_000}
                prefix={currencyConfig.symbol}
              />

              <SliderField
                label="Current Savings Already Set Aside"
                value={currentSavings}
                onChange={setCurrentSavings}
                min={0}
                max={targetAmount}
                step={100_000}
                prefix={currencyConfig.symbol}
              />

              <SliderField
                label="Expected Annual Return Rate"
                value={annualReturnRate}
                onChange={setAnnualReturnRate}
                min={0}
                max={30}
                step={0.5}
                suffix="%"
              />

              {/* Timeframe Quick Buttons */}
              <div>
                <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">
                  Target Timeframe
                </label>
                <div className="grid grid-cols-4 gap-2 mb-3">
                  {[6, 12, 24, 36].map((m) => (
                    <button
                      key={m}
                      type="button"
                      onClick={() => setTimeframeMonths(m)}
                      className={`py-2 text-xs font-semibold rounded-lg border transition-all ${
                        timeframeMonths === m
                          ? 'bg-emerald-600 border-emerald-600 text-white'
                          : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:border-emerald-500'
                      }`}
                    >
                      {m < 12 ? `${m} Months` : `${m / 12} ${m === 12 ? 'Year' : 'Years'}`}
                    </button>
                  ))}
                </div>
                <SliderField
                  label="Custom Duration (Months)"
                  value={timeframeMonths}
                  onChange={setTimeframeMonths}
                  min={1}
                  max={120}
                  step={1}
                  suffix=" mo"
                />
              </div>
            </div>
          </Card>
        </div>

        <div className="lg:col-span-6 space-y-6">
          <Card>
            <h2 className="text-base font-bold text-slate-900 dark:text-white mb-2">
              Capital Contribution Breakdown
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mb-6">
              Comparing your direct out-of-pocket savings against compounding returns.
            </p>

            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-100 dark:border-slate-800 space-y-3">
                <div className="flex justify-between items-center text-xs sm:text-sm">
                  <span className="text-slate-600 dark:text-slate-400">Total Deposits You Make</span>
                  <span className="font-bold text-slate-900 dark:text-white">{format(results.totalDeposited)}</span>
                </div>
                <div className="flex justify-between items-center text-xs sm:text-sm text-emerald-600 dark:text-emerald-400 font-semibold">
                  <span>Compounded Interest Generated</span>
                  <span>+ {format(results.interestEarned)}</span>
                </div>
                <div className="pt-2 border-t border-slate-200 dark:border-slate-700 flex justify-between items-center text-sm font-bold text-slate-900 dark:text-white">
                  <span>Terminal Goal Target Value</span>
                  <span>{format(targetAmount)}</span>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/40 text-xs text-emerald-900 dark:text-emerald-300 space-y-1.5">
                <div className="font-bold flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-emerald-600" />
                  <span>The Power of Compounding</span>
                </div>
                <p className="leading-relaxed">
                  Compounding interest pays for <strong>{((results.interestEarned / targetAmount) * 100).toFixed(1)}%</strong> of your total target goal, saving you {format(results.interestEarned)} in out-of-pocket earnings!
                </p>
              </div>
            </div>
          </Card>
        </div>
      </div>

      {/* Explainable Result */}
      <ExplainableResult data={explainableData} />
    </div>
  );
};
